export interface MenuItem {
  id: string;
  name: string;
  description: string;
  price: number;
  image: string;
  category: MenuCategory;
  isVeg: boolean;
  isSpicy: boolean;
}

export interface CartItem extends MenuItem {
  quantity: number;
}

export interface OrderItem {
  id: string;
  name: string;
  quantity: number;
  price: number;
  notes?: string;
}

export interface Order {
  id: string; // The '?' is removed to match kitchen. ID will be generated by Firestore.
  tableNumber: number;
  items: OrderItem[];
  status: 'pending' | 'preparing' | 'ready' | 'served';
  orderTime: number; // Switched from timestamp
  estimatedTime?: number; // ETA in minutes
  etaSetAt?: number; // Timestamp when ETA was set
  totalAmount: number; // Switched from total
  customerName?: string;
  specialInstructions?: string;
}

export type MenuCategory = 'appetizers' | 'main-course' | 'breads' | 'rice' | 'sweets' | 'drinks';

export const MENU_CATEGORIES: Array<{ id: MenuCategory; label: string; icon: string }> = [
  { id: 'appetizers', label: 'Appetizers', icon: '🥗' },
  { id: 'main-course', label: 'Main Course', icon: '🍛' },
  { id: 'breads', label: 'Breads', icon: '🫓' },
  { id: 'rice', label: 'Rice', icon: '🍚' },
  { id: 'sweets', label: 'Sweet Dish', icon: '🍮' },
  { id: 'drinks', label: 'Drinks', icon: '🥤' }
];